# Generated by Django 6.0.7 on 2026-07-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionCursos',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('curso_id', models.IntegerField()),
                ('nombre_curso_anterior', models.CharField(max_length=100)),
                ('nombre_curso_nuevo', models.CharField(max_length=100)),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'Actualizacion_Cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActualizacionDetallePagos',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_id', models.IntegerField()),
                ('subtotal_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'Actualizacion_Detalle_Pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActualizacionEstudiantes',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('estudiante_id', models.IntegerField()),
                ('usuario_anterior', models.CharField(max_length=50)),
                ('usuario_nuevo', models.CharField(max_length=50)),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'Actualizacion_Estudiantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActualizacionEvaluaciones',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('evaluacion_id', models.IntegerField()),
                ('calificacion_anterior', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calificacion_nueva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'Actualizacion_Evaluaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActualizacionInscripciones',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('inscripcion_id', models.IntegerField()),
                ('folio_inscripcion_anterior', models.CharField(max_length=20)),
                ('folio_inscripcion_nuevo', models.CharField(max_length=20)),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'Actualizacion_Inscripciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActualizacionInstructores',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('instructor_id', models.IntegerField()),
                ('nombre_completo_anterior', models.CharField(max_length=100)),
                ('nombre_completo_nuevo', models.CharField(max_length=100)),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'Actualizacion_Instructores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActualizacionPagos',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('pago_id', models.IntegerField()),
                ('monto_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'Actualizacion_Pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaCursos',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('curso_id', models.IntegerField()),
                ('accion', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'Auditoria_Cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaDetallePagos',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_id', models.IntegerField()),
                ('accion', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'Auditoria_Detalle_Pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaEstudiantes',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('estudiante_id', models.IntegerField()),
                ('accion', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'Auditoria_Estudiantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaEvaluaciones',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('evaluacion_id', models.IntegerField()),
                ('accion', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'Auditoria_Evaluaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaInscripciones',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('inscripcion_id', models.IntegerField()),
                ('accion', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'Auditoria_Inscripciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaInstructores',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('instructor_id', models.IntegerField()),
                ('accion', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'Auditoria_Instructores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaPagos',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('pago_id', models.IntegerField()),
                ('accion', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'Auditoria_Pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('curso_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('duracion_horas', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Cancelado', 'Cancelado'), ('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Finalizado', 'Finalizado'), ('Activa', 'Activa')], default='Activo', max_length=20)),
                ('cupo_maximo', models.IntegerField()),
            ],
            options={
                'db_table': 'Cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('detalle_id', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Detalle_Pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EliminacionCursos',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('curso_id', models.IntegerField()),
                ('fecha_eliminacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'Eliminacion_Cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EliminacionDetallePagos',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_id', models.IntegerField()),
                ('fecha_eliminacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'Eliminacion_Detalle_Pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EliminacionEstudiantes',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('estudiante_id', models.IntegerField()),
                ('fecha_eliminacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'Eliminacion_Estudiantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EliminacionEvaluaciones',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('evaluacion_id', models.IntegerField()),
                ('fecha_eliminacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'Eliminacion_Evaluaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EliminacionInscripciones',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('inscripcion_id', models.IntegerField()),
                ('fecha_eliminacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'Eliminacion_Inscripciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EliminacionInstructores',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('instructor_id', models.IntegerField()),
                ('fecha_eliminacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'Eliminacion_Instructores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EliminacionPagos',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('pago_id', models.IntegerField()),
                ('fecha_eliminacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'Eliminacion_Pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('estudiante_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.BinaryField(max_length='max')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('numero_documento', models.BinaryField(max_length='max')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Estudiantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('evaluacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Evaluaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('inscripcion_id', models.AutoField(primary_key=True, serialize=False)),
                ('folio_inscripcion', models.CharField(max_length=20)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Cancelado', 'Cancelado'), ('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Finalizado', 'Finalizado'), ('Activa', 'Activa')], default='Activa', max_length=20)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Inscripciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=50)),
                ('cedula_profesional', models.BinaryField(max_length='max')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.BinaryField(max_length='max')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Cancelado', 'Cancelado'), ('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Finalizado', 'Finalizado'), ('Activa', 'Activa')], default='Activo', max_length=20)),
            ],
            options={
                'db_table': 'Instructores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(max_length=30)),
                ('referencia_pago', models.BinaryField(max_length='max')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Pagos',
                'managed': False,
            },
        ),
    ]
