# Generated by Django 6.0.7 on 2026-07-19 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'managed': True},
        ),
    ]
