# Generated by Django 6.0.7 on 2026-07-22 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_estudiante_options_alter_instructor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'managed': False},
        ),
    ]
