# Generated by Django 6.0.7 on 2026-07-22 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_estudiante_options_alter_instructor_options'),
    ]

    operations = [
    ]
