# Generated by Django 6.0.7 on 2026-07-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='numero_empleado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificador de Usuario'),
        ),
    ]
