# Generated by Django 6.0.7 on 2026-07-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_perfilusuario_numero_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='nivel_acceso',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Instructor'), (3, 'Estudiante')], default=3, verbose_name='Nivel de Acceso'),
        ),
    ]
