# Generated by Django 6.0.7 on 2026-07-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_perfilusuario_nivel_acceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='numero_empleado',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='numero_usuario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Usuario'),
        ),
    ]
